---
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: create-trusted-artifact
spec:
  description: >-
    This stepaction creates a trusted artifact. It does nothing if a .skip-trusted-artifacts file exists
    in root folder.
  image: quay.io/redhat-appstudio/build-trusted-artifacts@sha256:b31dc501d5068e30621e51681a2921d4e43f5a030ab78c8991f83a5e774534a3
  env:
    # Set HOME variable to something else than `/` to avoid 'permission denied' problems when writing files.
    - name: HOME
      value: /tekton/home
    - name: ORAS_OPTIONS
      value: $(params.orasOptions)
  params:
    - name: ociStorage
      type: string
      default: "empty"
    - name: workDir
      type: string
    - name: sourceDataArtifact
      type: string
      default: ""
    - name: orasOptions
      type: string
      default: ""
      description: oras options to pass to Trusted Artifacts calls
  args:
    - create
    - --store
    - $(params.ociStorage)
    - $(params.sourceDataArtifact)=$(params.workDir)
